# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main","test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Test
        run: |
          git fetch                         # fetch branches
          git status

          git checkout test       # checkout to your branch
          git branch 

          git checkout main -- test.txt # copy files from the source branch
          git branch 

          git add -A

          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)

          git push origin test # push to remote branch
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#'
          tokenSuffix: '#'
          files: '["**/*.json"]'
        env:
          TEST:  ${{ secrets.TEST}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: 'files'
          # A file, directory or wildcard pattern that describes what to upload
          path: .
